[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  HUGO_VERSION = "0.89.4"
  GO_IMPORT_PATH = "github.com/0xdecaff/corruptions.io"

[context.deploy-preview]
  command = "npm run build:preview"
